# Generated by Django 5.2.8 on 2025-11-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=150)),
                ('actor', models.CharField(max_length=150)),
                ('verb', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('post', 'Post')], max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
