# Generated by Django 5.2.8 on 2025-11-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('post', 'Post'), ('comment', 'Comment')], max_length=20),
        ),
    ]
